SRCS_FILES=	Components/InventoryComponent.cpp			\
		Components/Movement2DComponent.cpp			\
		Components/NameComponent.cpp				\
									\
		Updaters/ActionPlanningUpdater.cpp			\
		Updaters/GrowableUpdater.cpp				\
		Updaters/InventoryUpdater.cpp				\
		Updaters/MovingEntitiesUpdater.cpp			\
									\
		RenderUpdaters/CameraRenderUpdater.cpp 			\
		RenderUpdaters/DebugGridRenderUpdater.cpp		\
		RenderUpdaters/DemoImguiRenderUpdater.cpp		\
		RenderUpdaters/DebugShortcutsRenderUpdater.cpp		\
		RenderUpdaters/EntityCreatorRenderUpdater.cpp		\
		RenderUpdaters/FPSPanelRenderUpdater.cpp		\
		RenderUpdaters/GridRenderUpdater.cpp		\
		RenderUpdaters/GridControlPanelRenderUpdater.cpp	\
		RenderUpdaters/InventoryPanelRenderUpdater.cpp		\
		RenderUpdaters/MoveOrderRenderUpdater.cpp		\
		RenderUpdaters/SelectionRectangleRenderUpdater.cpp	\
		RenderUpdaters/SelectedRenderUpdater.cpp	 	\
		RenderUpdaters/StaticMeshRenderUpdater.cpp 		\
		RenderUpdaters/SteveRenderUpdater.cpp			\
		RenderUpdaters/WorldTickerRenderUpdater.cpp		\
									\
		WorldComponents/Camera.cpp				\
		WorldComponents/SquareGrid.cpp				\
									\
		utils/EntityFinder.cpp					\
		utils/Pathfinding.cpp					\
		utils/TransformationHelper.cpp				\
									\
		EntityDescriptors.cpp					\
		main.cpp						\

NATIVE_NAME=	exec

include ../common.make
