SRCS_FILES=	Camera.cpp 			\
		CameraRenderUpdater.cpp 	\
		DebugGridRenderUpdater.cpp	\
		DemoImguiRenderUpdater.cpp	\
		DebugShortcutsRenderUpdater.cpp	\
		EntityCreatorRenderUpdater.cpp	\
		FPSPanelRenderUpdater.cpp	\
		HexagonalGrid.cpp		\
		HexaGridRenderUpdater.cpp	\
		HexaGridControlPanelRenderUpdater.cpp	\
		InventoryComponent.cpp		\
		InventoryPanelRenderUpdater.cpp	\
		ItemComponent.cpp		\
		Movement2DComponent.cpp		\
		MoveOrderRenderUpdater.cpp	\
		MovingEntitiesUpdater.cpp	\
		NameComponent.cpp		\
		Pathfinding.cpp			\
		Position2DComponent.cpp		\
		SaveLoaderRenderUpdater.cpp 	\
		SelectableComponent.cpp		\
		SelectionRectangleRenderUpdater.cpp	\
		SelectedRenderUpdater.cpp 	\
		StaticMeshComponent.cpp 	\
		StaticMeshRenderUpdater.cpp 	\
		SteveRenderUpdater.cpp		\
		SteveAnimationComponent.cpp	\
		TransformationHelper.cpp	\
		main.cpp			\

NATIVE_NAME=	exec

include ../common.make
