SRCS_FILES=	AsteroidCreatorUpdater.cpp	\
		BasicTextDrawer.cpp		\
		CollisionUpdater.cpp		\
		EntityDescriptors.cpp		\
		LifespanUpdater.cpp		\
		MeshDisplayUpdater.cpp		\
		MovingEntitiesUpdater.cpp	\
		PlayerControlUpdater.cpp	\
		PlayerCreatorUpdater.cpp	\
		PlayerMovementUpdater.cpp	\
		ProjectileUpdater.cpp		\
		ProjectionViewUpdater.cpp	\
		RandomDirector.cpp		\
		SaveLoaderRenderUpdater.cpp	\
		Score.cpp			\
		ScoreRenderUpdater.cpp		\
		ScreenBorderTeleportUpdater.cpp	\
		ShooterComponent.cpp		\
		SubdivisionUpdater.cpp		\
		UFOUpdater.cpp			\
		WreckageUpdater.cpp		\
		main.cpp

NATIVE_NAME=	asteroids

include ../common.make
