SRCS_FILES=	main.cpp				\
		BasicTextDrawer.cpp			\
		EntityDescriptors.cpp			\
							\
		Components/ShooterComponent.cpp		\
							\
		WorldComponents/Lives.cpp		\
		WorldComponents/RandomDirector.cpp	\
		WorldComponents/Score.cpp		\
							\
		Updaters/AsteroidCreatorUpdater.cpp	\
		Updaters/CollisionUpdater.cpp		\
		Updaters/LifespanUpdater.cpp		\
		Updaters/MovingEntitiesUpdater.cpp	\
		Updaters/PlayerCreatorUpdater.cpp	\
		Updaters/PlayerMovementUpdater.cpp	\
		Updaters/ProjectileUpdater.cpp		\
		Updaters/ScreenBorderTeleportUpdater.cpp\
		Updaters/SubdivisionUpdater.cpp		\
		Updaters/UFOUpdater.cpp			\
		Updaters/WreckageUpdater.cpp		\
							\
		RenderUpdaters/LivesRenderUpdater.cpp	\
		RenderUpdaters/MeshDisplayUpdater.cpp	\
		RenderUpdaters/ProjectionViewUpdater.cpp\
		RenderUpdaters/SaveLoaderRenderUpdater.cpp\
		RenderUpdaters/ScoreRenderUpdater.cpp	\
		RenderUpdaters/PlayerControlUpdater.cpp	\


NATIVE_NAME=	asteroids

include ../common.make
