SRCS_FILES=	AsteroidComponent.cpp		\
		AsteroidCreatorUpdater.cpp	\
		CollidableComponent.cpp		\
		CollisionUpdater.cpp		\
		LifespanComponent.cpp		\
		LifespanUpdater.cpp		\
		MeshComponent.cpp		\
		MeshDisplayUpdater.cpp		\
		MovingEntitiesUpdater.cpp	\
		PlayerComponent.cpp		\
		PlayerControlUpdater.cpp	\
		PlayerCreatorUpdater.cpp	\
		PlayerMovementUpdater.cpp	\
		ProjectileComponent.cpp		\
		ProjectileUpdater.cpp		\
		PositionComponent.cpp		\
		ProjectionViewUpdater.cpp	\
		SaveLoaderRenderUpdater.cpp	\
		ScreenBorderTeleportUpdater.cpp	\
		ShooterComponent.cpp		\
		main.cpp

NATIVE_NAME=	asteroids

include ../common.make
